version: '3'

services:

  nats:
    container_name: nats
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"

  client-gateway:
    container_name: client-gateway
    build: ./client-gateway
    ports: 
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats:4222
  products-ms:
    container_name: products-ms
    build: ./products-ms
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats:4222
      - DATABASE_URL=file:./dev.db

  orders-db:
    container_name: orders-db
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=orders
  
  orders-ms:
    depends_on:
      - orders-db
    container_name: orders-ms
    build: ./orders-ms
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats:4222
      - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/orders?schema=public

  payments-ms:
    container_name: payments-ms
    build: ./payments-ms
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    command: npm run start:dev
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats:4222
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}

      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - PAYMENTS_SUCCESS_URL=${PAYMENTS_SUCCESS_URL}
      - PAYMENTS_CANCEL_URL=${PAYMENTS_CANCEL_URL}